apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypublicip-amd64-control
  labels:
    app: mypublicip
    arch: amd64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypublicip
      arch: amd64
  template:
    metadata:
      labels:
        app: mypublicip
        arch: amd64
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: control
      containers:
        - name: app
          image: docker.io/meesam110/archprint:demo1
          imagePullPolicy: Always
          command: ["python", "/app/scripts/public_ip.py"]
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"

